// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjsfulbimcvoaqflfbir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqc2Z1bGJpbWN2b2FxZmxmYmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODA2NTIsImV4cCI6MjA2NDc1NjY1Mn0.y3AXpwq6fazpDdWP5zDXL2C3cWOdVMH3540_yZLqyrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);